export { default as globalApi } from './globalApi'
export { default as lightOperateApi } from './lightOperateApi'
export { default as lightHomeApi } from './lightHomeApi'
export { default as loginApi } from './loginApi'
export { default as heavyOperateApi } from './heavyOperateApi'
export { default as heavyHomeApi } from './heavyHomeApi'
